### ISSUE TITLE
training scrip gives error message 

### ISSUE THREAD

**Issue by ysawires12345678** [ytnobody/Plass#1]
Hello,
I tried to run the traing=ing script with the following command (not including the default parameters)
python train.py -p strain 13 plasmid  -c strain 13 chromosome  -o output directory
and I got the following message 
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    import plasclass_utils as utils
ModuleNotFoundError: No module named 'plasclass_utils'
Would you please be able to help me with this
Thank You

**Comment by ytnobody** [comment]
@ysawires12345678 
Maybe your post targets other project.
https://github.com/martin-steinegger/plass-analysis
And my project is not related with martin-steinegger/plass-analysis .

Best regards.
